language: php

sudo: false

php:
  - 7.0

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - vendor

install:
  - composer install --no-interaction

# Declare which versions of WordPress to test against.
env:
    - WP_VERSION=master

services:
    - mysql

install:
  - composer install

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  - pwd
  # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  # Set up WordPress configuration.
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # Create WordPress database.
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  # Switch back to the plugin dir
  - cd $TRAVIS_BUILD_DIR

script:
  - phpunit --verbose
  - phpunit --verbose -c tests/php/multisite.xml
  - phpunit --verbose -c tests/php/whitelisted.xml
