name: Build release zip

on:
  workflow_dispatch:
  push:
   branches:
    - trunk

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vendor
        id: cache-composer
        uses: actions/cache@v3
        env:
          cache-name: cache-vendor
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node version and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-optional

      - name: Install Composer dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-dev

      - name: Build plugin
        run: npm run build

      - name: Generate ZIP file
        run: bash bin/build-zip.sh

      - name: Unzip the file (prevents double zip problem)
        run: unzip ${{ github.event.repository.name }}.zip -d zipfile

      - name: Upload the ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: zipfile
          retention-days: 5