on:
  push:
    branches:
      - e2e/55-default-admin-settings

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        core:
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.8'}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

    - name: Set up WP environment
      run: npm run env start

    - name: Test
      run: npm run cypress:run
