name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  check-diffs:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.files-changed.outputs.RSA_FILES_CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get updated JS files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
            files: |
              **/*.php
              **/*.js
              **/*.json
              **/*.css
              readme.txt

      - id: files-changed
        run: |
          if [[ ( "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ) || "${{ github.event_name }}" == "push" ]]; then
            echo "RSA_FILES_CHANGED=yes" >> $GITHUB_OUTPUT
          fi

  build: 
    uses: 10up/restricted-site-access/.github/workflows/build-release-zip.yml@develop
  cypress:
    runs-on: ubuntu-latest
    needs: [check-diffs, build]
    if: needs.check-diffs.outputs.has_changed == 'yes'
    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install PHP dependencies
      run: composer i

    - name: Download build zip
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Set the core version and plugins config 
      run: ./tests/bin/set-wp-config.js --core=${{ matrix.core.version }} --plugins=./${{ github.event.repository.name }},./tests/rsa-seeder
    - name: Set up WP environment
      run: npm run env:start

    - name: Test
      run: npm run cypress:run

    - name: Update summary
        run: |
          npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
          rm -rf ./tests/cypress/reports/mochawesome-*.json
          npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
          npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
          cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY

    - name: Make artifacts available
        uses: actions/upload-artifact@v3
        if: failure()
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
            ${{ github.workspace }}/tests/cypress/reports/
