name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  check-diffs:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.files-changed.outputs.RSA_FILES_CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get updated JS files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
            files: |
              **/*.php
              **/*.js
              **/*.json
              **/*.css

      - id: files-changed
        run: |
          if [[ ( "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ) || "${{ github.event_name }}" == "push" ]]; then
            echo "RSA_FILES_CHANGED=yes" >> $GITHUB_OUTPUT
          fi

  cypress:
    runs-on: ubuntu-latest
    needs: check-diffs
    if: needs.check-diffs.outputs.has_changed == 'yes'
    strategy:
      matrix:
        core:
          - {name: 'WP 6.1-RC4', version: 'https://wordpress.org/wordpress-6.1-RC5.zip'}
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install PHP dependencies
      run: composer i

    - name: Install JS dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Test
      run: npm run cypress:run --record

    - name: Get working directory
      run: pwd

    - name: Upload RSA artifcats
      uses: actions/upload-artifact@v2.3.0
      if: always()
      with:
        name: 'Cypress artifacts'
        path: tests/cypress/videos/
        if-no-files-found: warn
