name: ESLint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run JS linting
      run: npm run lint:js