name: ESLint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  check-diffs:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.files-changed.outputs.RSA_JS_FILES_CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get updated files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
            files: |
              **/*.js

      - id: files-changed
        run: |
          if [[ ( "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ) || "${{ github.event_name }}" == "push" ]]; then
            echo "RSA_JS_FILES_CHANGED=yes" >> $GITHUB_OUTPUT
          fi
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    needs: check-diffs
    if: needs.check-diffs.outputs.has_changed == 'yes'
    steps:
    - uses: actions/checkout@v2
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run JS linting
      run: npm run lint:js