name: ESLint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: install node v16
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          assets/js/src/*.js
          **/*.json

    - name: Install dependencies
      run: npm install

    - name: Run JS linting
      run: |
        if [[ "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ]]; then
          npx eslint ${{ steps.changed-files.outputs.all_changed_files }}
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          npm run lint:js
        fi