name: PHP Linting

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  php-compatibility:
    name: Sniffs and Compatibility

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, cs2pr
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: WPCS check
        run: ./vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: PHP Compatibility check
        run: ./vendor/bin/phpcs . -q -n --standard=PHPCompatibilityWP --ignore=vendor --extensions=php --runtime-set testVersion 7.4- --report=checkstyle | cs2pr
